In [1]:
#Resumo dos Códigos de Matrizes Inversa, Transposta e Determinante - Algébra Linear
#Aluna: Noemi Soares Gonçalves da Silva  RA:00000851329

# Matriz Transposta
#### A transposta de uma matriz MA é uma matriz que possui os mesmos elementos de MA, mas postos em posições diferentes. Pode-se obter transportando ordenadamente os elementos das linhas de MA para as colunas de MA transposta.

In [1]:
import numpy as np # importando a biblioteca numpy padrão do Python

In [2]:
# criando a função de matriz transposta
def transposta():
    
    # recebe a quantidade de linhas da matriz
    linha = int(input("Informe quantas linhas tem sua matriz: ")) 
    # recebe a quantidade de colunas da matriz
    coluna = int(input("Informe quantas colunas tem sua matriz: ")) 
    
    # comandos de ir para a próxima linha
    print("\n") 
    
    # iniciando uma matriz de números reais com linhas e colunas definidas
    A = np.empty([linha,coluna], dtype = float)

    # estrutura for aninhada que recebe os elementos da matriz
    for i in range(0, linha):
        for j in range(0, coluna):
            A[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1,j + 1)))

    #imprime na tela a matriz original
    print("\n\nA matriz digitada é:\n\n{}\n\n".format(A))

    # definindo a matriz transposta com uma função do numpy
    A_T = np.transpose(A) 

    # imprime na tela a matriz transposta
    print("A matriz transposta é:\n\n{}\n\n". format(A_T))

    # definindo a matriz transposta da matriz A_T, voltando a ser a matriz A
    A = np.transpose(A_T)

    # imprime na tela a matriz tranposta da mesma já transposta, ou seja, retornará a matriz original
    print("A matriz transposta da transpostada é:\n\n{}".format(A))
    
    # função não retorna nenhum valor
    return None

In [3]:
# imprimindo a função criada
transposta()

Informe quantas linhas tem sua matriz:  2
Informe quantas colunas tem sua matriz:  3


Insira o elemento [1][1] da matriz:  1
Insira o elemento [1][2] da matriz:  2
Insira o elemento [1][3] da matriz:  3
Insira o elemento [2][1] da matriz:  4
Insira o elemento [2][2] da matriz:  5
Insira o elemento [2][3] da matriz:  6




A matriz digitada é:

[[1. 2. 3.]
 [4. 5. 6.]]


A matriz transposta é:

[[1. 4.]
 [2. 5.]
 [3. 6.]]


A matriz transposta da transpostada é:

[[1. 2. 3.]
 [4. 5. 6.]]


# Matriz Inversa
#### A matriz inversa ou matriz invertível é um tipo de matriz quadrada, ou seja, que possui o mesmo número de linhas (m) e colunas (n). Ela ocorre quando o produto de duas matrizes resulta numa matriz identidade de mesma ordem (mesmo número de linhas e colunas).

In [1]:
# importando a biblioteca de funções numpy
import numpy as np 

In [2]:
# função que calcula a matriz inversa
def inversa():

    print("Progama que calcula a matriz inversa")

    # variáveis que recebem a quantidade de linhas e colunas da matriz
    linha = int(input("Informe a quantidade de linhas da sua matriz: "))
    coluna = int(input("Informe a quantidade de colunas de sua matriz: "))

    # inicializando a matriz com seu devido tamanho
    matriz = np.empty([linha,coluna], dtype = float)

    # estrutura de repetição for que permite introduzir os elementos da matriz
    for i in range(0, linha):
        for j in range(0, coluna):
            matriz[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))

    # imprime a matriz digitada na tela
    print("\nA matriz digitada é:\n\n{}\n\n".format(matriz))

    # calcula a matriz inversa ou retorna uma mensagem de aviso que a matriz não possui inversa
    if(np.linalg.det(matriz) != 0):
        inversa = np.linalg.pinv(matriz)
        #imprime a matriz inversa
        print("A matriz inversa é:\n\n{}\n\n".format(inversa))
    else:
        print("\nA matriz não é inversível.")
        
    # função não retorna nenhum valor
    return None

In [3]:
# imprimindo a função inversa
inversa()

Progama que calcula a matriz inversa


Informe a quantidade de linhas da sua matriz:  3
Informe a quantidade de colunas de sua matriz:  3
Insira o elemento [1][1] da matriz:  1
Insira o elemento [1][2] da matriz:  5
Insira o elemento [1][3] da matriz:  6
Insira o elemento [2][1] da matriz:  2
Insira o elemento [2][2] da matriz:  5
Insira o elemento [2][3] da matriz:  8
Insira o elemento [3][1] da matriz:  2
Insira o elemento [3][2] da matriz:  5
Insira o elemento [3][3] da matriz:  7



A matriz digitada é:

[[1. 5. 6.]
 [2. 5. 8.]
 [2. 5. 7.]]


A matriz inversa é:

[[-1.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 4.00000000e-01 -1.00000000e+00  8.00000000e-01]
 [-1.58676765e-16  1.00000000e+00 -1.00000000e+00]]




# Determinante 

In [1]:
# Importa Funções da biblioteca Numpy
import numpy as np 

In [2]:
# função que calcula o determinante de uma matriz
def determinante():
    
    # Recebe a ordem da matriz
    qtd = int(input('Informe o ordem da matriz: ')) 
    
    # Inicializa a matriz, ainda com 'lixo de endereços de memória' nele
    matriz = np.empty([qtd, qtd], dtype = float) 
    print('\n')

    #Adiciona elementos na matriz
    for i in range(0, qtd):
        for j in range(0, qtd):
            matriz[i][j] = float(input('Digite [{}][{}] da matriz: '.format(i + 1, j + 1)))

    #Imprime a matriz
    print('\nA matriz é:\n', matriz)

    #a variável 'determinante' recebe o determinante da matriz
    determinante = np.linalg.det(matriz)

    #Imprime o determinante
    print('\nO determinante da matriz é: {:.2f}.'.format(determinante))
    
    # função não retorna nada
    return None

In [3]:
# imprimindo a função determinante
determinante()

Informe o ordem da matriz:  3


Digite [1][1] da matriz:  1
Digite [1][2] da matriz:  2
Digite [1][3] da matriz:  3
Digite [2][1] da matriz:  3
Digite [2][2] da matriz:  4
Digite [2][3] da matriz:  4
Digite [3][1] da matriz:  7
Digite [3][2] da matriz:  8
Digite [3][3] da matriz:  9



A matriz é:
 [[1. 2. 3.]
 [3. 4. 4.]
 [7. 8. 9.]]

O determinante da matriz é: -6.00.
