In [10]:
#Códigos de Sistemas Lineares - Algébra Linear


**ENCONTRE A SOLUÇÃO DOS SISTEMAS**

**Sistema 1**

In [11]:
# importando a biblioteca numpy
import numpy as np 

In [23]:
# declarar as matrizes do exemplo acima
A = np.array([[1,0,5,8],[5,0,0,-4.5],[0,4,2.5,-0.7],[8,-0.8,-5,8]])
B = np.array([[-7],[2],[-1],[-0.15]])

# Encontrar a inversa de A
A_I = np.linalg.inv(A) #Função que encontra a matriz inversa

# Encontrando X
X = np.dot(A_I,B) # Função que realiza mutiplicação entre matrizes sem especificador de tipo
# X = np.linalg.solve(A,B) #Função alternativa que resolve Sistemas Lineares

In [24]:
# imprime a matriz A dos coeficientes de X e Y
print("{}".format(A)) 

[[ 1.   0.   5.   8. ]
 [ 5.   0.   0.  -4.5]
 [ 0.   4.   2.5 -0.7]
 [ 8.  -0.8 -5.   8. ]]


In [25]:
# imprime a matriz A inversa
print("{}".format(A_I)) 

[[ 0.03511053  0.13055917  0.00780234  0.0390117 ]
 [-0.07477243 -0.07433897  0.26116168  0.05580841]
 [ 0.13055917  0.09733853 -0.0154313  -0.07715648]
 [ 0.0390117  -0.07715648  0.00866927  0.04334634]]


In [26]:
# imprime a matriz B resultado dos sistemas lineares
print("{}".format(B)) 

[[-7.  ]
 [ 2.  ]
 [-1.  ]
 [-0.15]]


In [27]:
# imprime a matrix , o  conjunto solução desse sistema
print("{}".format(X)) 

[[ 0.00169051]
 [ 0.10519614]
 [-0.69223234]
 [-0.4425661 ]]


**Sistema 2**

In [34]:
# declarar as matrizes do exemplo acima
A = np.array([[-0.53,0.33,5,-8,1,-1,1],[1,0,5,0,0,0,0],[0,-1.14,8.7,9.71,0,0,-8],
              [0,0,0,0,0,5,-8],[0,0,-1.14,14,-5,0,0],[0,0,8,0,0,5,-9],[0,0,0,0,1,0,0]])
B = np.array([[0],[7],[8.2],[0],[-1],[9.7],[-14]])

# Encontrar a inversa de A
A_I = np.linalg.inv(A) #Função que encontra a matriz inversa

# Encontrando X
X = np.dot(A_I,B) # Função que realiza mutiplicação entre matrizes sem especificador de tipo
# X = np.linalg.solve(A,B) #Função alternativa que resolve Sistemas Lineares

In [35]:
# imprime a matriz A dos coeficientes de X e Y
print("{}".format(A)) 

[[-0.53  0.33  5.   -8.    1.   -1.    1.  ]
 [ 1.    0.    5.    0.    0.    0.    0.  ]
 [ 0.   -1.14  8.7   9.71  0.    0.   -8.  ]
 [ 0.    0.    0.    0.    0.    5.   -8.  ]
 [ 0.    0.   -1.14 14.   -5.    0.    0.  ]
 [ 0.    0.    8.    0.    0.    5.   -9.  ]
 [ 0.    0.    0.    0.    1.    0.    0.  ]]


In [36]:
# imprime a matriz A inversa
print("{}".format(A_I)) 

[[ 3.68176455e-01  1.19513352e+00  1.06577395e-01  1.14716032e+00
   1.36467510e-01 -1.07352503e+00  3.14161093e-01]
 [ 3.52088620e+00  1.86606969e+00  1.42010918e-01  3.95279631e+00
   1.91344026e+00 -3.24861907e+00  6.04631508e+00]
 [-7.36352910e-02 -3.90267042e-02 -2.13154790e-02 -2.29432065e-01
  -2.72935019e-02  2.14705006e-01 -6.28322187e-02]
 [-5.99601655e-03 -3.17788877e-03 -1.73568900e-03 -1.86823253e-02
   6.92061006e-02  1.74831219e-02  3.52026519e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [-9.42531725e-01 -4.99541814e-01 -2.72838131e-01 -1.13673043e+00
  -3.49356825e-01  1.14822408e+00 -8.04252399e-01]
 [-5.89082328e-01 -3.12213634e-01 -1.70523832e-01 -8.35456517e-01
  -2.18348015e-01  7.17640051e-01 -5.02657750e-01]]


In [37]:
# imprime a matriz B resultado dos sistemas lineares
print("{}".format(B)) 

[[  0. ]
 [  7. ]
 [  8.2]
 [  0. ]
 [ -1. ]
 [  9.7]
 [-14. ]]


In [38]:
# imprime a matrix , o  conjunto solução desse sistema
print("{}".format(X)) 

[[  -5.70804634]
 [-103.84647906]
 [   2.54160927]
 [  -4.86446896]
 [ -14.        ]
 [  17.01259863]
 [  10.63287415]]
